"""empty message

Revision ID: 3da074383b1
Revises: 42c9784b460
Create Date: 2015-11-24 20:51:24.804848

"""

# revision identifiers, used by Alembic.
revision = '3da074383b1'
down_revision = '42c9784b460'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_urls', sa.Column('crawled', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_urls', 'crawled')
    ### end Alembic commands ###
